.gitignore, android/app/BUCK, android/app/proguard-rules.pro, app/components/FormCell.js, app/components/FormData.js, app/components/FormList.js, app/components/FormNavigator.js, app/components/MapNavigator.js, app/components/SCForm.js, app/components/SCMap.js, app/components/SCStore.js, app/components/StoreCell.js, app/components/StoreList.js, app/components/StoreNavigator.js, index.android.js, index.ios.js, ios/SCMobile.xcodeproj/project.pbxproj, ios/SCMobile/AppDelegate.m, ios/SCMobile/Info.plist, ios/SCMobileTests/Info.plist, ios/SCMobileTests/SCMobileTests.m, ios/remote.scfg, package.json
**READY**
Update react-native to 0.27.2 and necessary dependencies
=> Update to react-native 0.27.2

android/app/src/main/java/com/scmobile/MainActivity.java
**READY**
A few sentences describing the overall goals of the pull request's commits.
```sh
```
* 
=> adding license header

.gitignore, android/app/build.gradle
**READY**
Ensure that we can build release APKs for the React Native apps.  More info can be found [here](https://facebook.github.io/react-native/docs/signed-apk-android.html)
```sh
```
* 
=> adding config to assemble release apk

package.json
**READY**
updating spatialconnect-js dependency to pull from npm
=> updating spatialconnect-js dependency to pull from npm

android/app/src/main/res/raw/config.scfg
**READY**
Config change
```sh
```
* 
=> renaming to use dev server

ios/SCMobile.xcodeproj/project.pbxproj, ios/SCMobile/AppDelegate.m
**READY**
Adds fabric crash monitoring to the mobile app
=> Adding Fabric to iOS app

app/components/SCMap.js, app/utils/map.js
=> Adding limit and layerIds to filter

app/SCMobile.js, app/actions/auth.js, app/actions/sc.js, app/components/LoginView.js, app/components/SideMenu.js, app/components/SignUpView.js, app/containers/AuthComponent.js, app/reducers/auth.js, app/style/style.js, app/utils/api.js
**READY**
Adds ability for users to sign up through the mobile application
* 
=> Add sign up form

app/actions/sc.js
**READY**
Reload forms, stores, token after successful login
* 
=> Reload after login

app/SCMobile.js, app/components/SideMenu.js, app/style/palette.js, app/style/style.js
=> fix colors

android/app/build.gradle
**READY**
Updating the version
```sh
```
* 
=> updating android dependency version

app/components/FormCell.js, app/components/SCForm.js, package.json
=> updating to use new form schema

app/components/SCMap.js, ios/SCMobile/Base.lproj/LaunchScreen.xib, package.json
**READY**
Fix filter. update scformschema. update launch screen color
* 
=> Fix filter. update scformschema. update launch screen color

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/scmobile/MainActivity.java, android/build.gradle
**READY**
Adds crashlytics to android app
=> adding crashlytics to android

.gitignore, android/app/BUCK, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/boundlessgeo/efc/MainActivity.java
=> renaming package to be consistent with ios

app/SCMobile.js, package.json
**READY**
- Small UI fixes
- v0.4.1
* 
=> UI hotfixes

android/app/src/main/java/com/boundlessgeo/efc/MainActivity.java, android/app/src/main/java/com/boundlessgeo/efc/MainApplication.java, app/actions/__tests__/auth-test.js, app/actions/auth.js, app/components/FeatureData.js, app/components/SCForm.js, app/components/SCMap.js, app/components/__tests__/__snapshots__/FeatureData-test.js.snap, app/utils/__mocks__/api.js, index.android.js, package.json, test-setup.js
=> Jest tests + updates for RN 0.30

.gitignore
**READY**
Updating `.gitignore`
=> ignore fabric api key configuration

app/ducks/sc.js
**READY**
Refactoring to use cross platform Alert component so it works on Android
=> use cross platform Alert instead of AlertIOS

ios/remote.scfg
**READY**
Updates remote config to match new spec
* 
=> Update remote config

android/app/build.gradle
**READY**
Upgrading the build tools to this version will make the build faster
=> updating build tools version so we can run the dex process in memory

app/components/SCMap.js, ios/SCMobile.xcodeproj/project.pbxproj, ios/SCMobile/SCBridge.h, ios/SCMobile/SCBridge.m
**READY**
SPACON-228
- Add tile support to `react-native-maps`
```sh
```
* 
=> Add tile support to React Native Maps

ios/SCMobile/Info.plist
**READY**
- Add `NSPhotoLibraryUsageDescription`
- Add `NSCameraUsageDescription`
=> Add Camera usage description

app/SCMobile.js, ios/SCMobile/Info.plist, ios/SCMobile/SCBridge.m, package.json
**READY**
- Add bindMapView to SCBridge
- Add Camera usage description keys
- Upgrade RN 0.34
```sh
```
* 
=> Add bindMapView to SCBridge

app/components/SCMap.js, app/containers/MapNavigator.js, app/ducks/sc.js, app/utils/map.js
**READY**
SPACON-238
- Query  stores with map bounding box onRegionChangeComplete
- Only show 100 features on the map at a time
```sh
```
* 
=> Query map with bbox on regionchangecomplete

app/ducks/sc.js
**READY**
SPACON-233
Enable the GPS when connecting spatialconnect
```sh
```
* 
=> enable the gps through bridge

app/ducks/sc.js
Ready
Request GPS permissions for android api >= 23
```sh
```
* 
=> Requesting gps perms for android api >=23

app/components/FormList.js, app/components/SCMap.js, app/components/StoreList.js, app/containers/FormNavigator.js, app/containers/StoreNavigator.js, ios/SCMobile/EFC.entitlements
**READY**
- Add entitlements file with Key Sharing capability
- Pull to refresh on form and store lists
- Throttle onRegionChangeComplete events
=> iOS Entitlements + pull to refresh + query throttle

app/components/SCForm.js
**READY**
SPACON-239 
After form submission, alert window appears with two options
- New Submission (clears form)
- Ok (Back to form list)
=> Add form submission alert

package.json
Ready
Updating image picker module
```sh
```
* 
=> updating image picker module

app/SCMobile.js, app/components/SCMap.js, app/components/SideMenu.js
=> Update font sizes

ios/SCMobile.xcodeproj/project.pbxproj, ios/SCMobile/Info.plist, ios/SCMobileTests/Info.plist
**READY/**
- Update iOS project file to add Entitlements file, MQTTFramework to carthage copy-frameworks, and automatic code signing identity
=> Project file updates

package.json
=> updating form schema version

app/components/LoginView.js, app/components/SignUpView.js, app/ducks/auth.js, app/ducks/sc.js, ios/SCMobile.xcodeproj/project.pbxproj
**READY**
- SPACON-321
- Gets backendUri from bridge
- Signs Up new users
```sh
```
* 
=> Add Sign Up

app/SCMobile.js, app/components/CreateMenu.js, app/components/LayerList.js, app/components/StoreCell.js, app/ducks/map.js, app/ducks/sc.js, app/style/style.js, ios/SCMobile/AppDelegate.m, ios/SCMobile/Info.plist, package.json
**READY**
- Shows status of store in Store List
- Shows downloading percentage if store is downloading
- Shows Stopped if store did not successfully start
- Requires Android SDK update for storeList bridge
```sh
```
* 
=> Feature: Show store status in UI

ios/SCMobile.xcodeproj/project.pbxproj
=> Add lumberjack to copyframeworks

app/ducks/map.js
**READY**
Use new filter creation api `sc.filter()`
* 
=> Fix filter creation

app/components/SCForm.js, app/ducks/map.js, package.json
=> Update form schema + RN version

android/app/build.gradle
=> ignoring some duplicate files included with auth0's jwt lib

android/app/build.gradle, android/build.gradle
**READY**
upgrading build tools to 2.2.3
```sh
```
* 
=> upgrading android gradle build tools

app/ducks/map.js
=> Use spatialconnect-js for addRasterLayers

android/app/src/main/java/com/boundlessgeo/efc/MainActivity.java
**READY**
Update service start method to match the sdk changes
=> renaming start method

app/components/SCForm.js
**READY**
Remove call to serialize feature b/c spatialconnect-js does this automatically now.
=> remove call to serialize b/c it's no longer needed

app/ducks/map.js
**READY**
Removing serialize b/c it's not needed anymore
=> remove serialize to match spatialconnect-js api

app/components/SCForm.js
**READY**
New spatialconnect-js API
```sh
```
* 
=> Create spatialFeature with properties object

README.md, android/app/src/main/java/com/boundlessgeo/efc/MainActivity.java
**READY**
Removing listening to notification for now, added jenkins build status badge
```sh
```
* 
=> Removed android notification and added jenkins build status

ios/SCMobile.xcodeproj/xcshareddata/xcschemes/SCMobile Release.xcscheme
**READY**
Release scheme needs to be checked in to enable builds on Jenkins
SPACON-450
=> Check in Release scheme

app/components/SCMap.js, app/containers/MapContainer.js, app/ducks/map.js, ios/Cartfile, package.json
=> Various fixes

app/AppNavigator.js, app/components/FeatureData.js, app/components/FeatureEdit.js, app/components/LoginView.js, app/components/PlaceHolder.js, app/components/SCForm.js, app/components/SCMap.js, app/components/SideMenu.js, app/components/__tests__/__snapshots__/FeatureEdit-test.js.snap, app/components/__tests__/__snapshots__/LoginView-test.js.snap, app/components/__tests__/__snapshots__/SCForm-test.js.snap, app/components/__tests__/__snapshots__/SCMap-test.js.snap, app/components/__tests__/__snapshots__/SignUpView-test.js.snap, app/containers/FormContainer.js, app/containers/MapContainer.js, app/containers/StoreContainer.js, app/containers/TestContainer.js, app/ducks/nav.js, app/style/style.js, package.json
**READY**
- Update `spatialconnect-form-schema` with form label fix
- Added `PlaceHolder` component to show when loading a view
- Add icons to menu
- Minor design updates
- Fix double navigation bug on logout
```sh
npm i
npm test
```
* 
=> fix form labels + add icons + design updates

app/components/CreateMenu.js, app/components/FeatureEdit.js, app/components/SCMap.js, app/components/SideMenu.js, app/ducks/map.js, app/style/style.js, app/utils/map.js, package.json
**IN DEVELOPMENT**
- Styles map features with store styles
- Run `npm i color` before running
=> Use SCStyles from store config

package.json
=> Use react-navigation version
